### ISSUE TITLE
Crash opening recipe book

### ISSUE THREAD

**Issue by LordMonoxide** [LordMonoxide/gradient#206]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MMFMLCorePlugin (MultiMine-1.12.2.jar)
Contact their authors BEFORE contacting forge

// Oh - I know what I did wrong!

Time: 2/22/18 8:55 PM
Description: Updating screen events

java.lang.IllegalArgumentException: Attempted to get the ID for a unknown recipe: net.minecraft.item.crafting.ShapedRecipes@d607d2c Name: gradient:grinding_head
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:53)
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:35)
	at net.minecraft.client.gui.recipebook.RecipeList.func_194210_a(SourceFile:34)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.lambda$updateCollections$0(GuiRecipeBook.java:161)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook$$Lambda$1285/212704632.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193003_g(GuiRecipeBook.java:159)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193014_a(GuiRecipeBook.java:96)
	at net.minecraft.client.gui.inventory.GuiInventory.func_146284_a(SourceFile:182)
	at lordmonoxide.gradient.inventory.GuiInventory3x3Crafting.func_146284_a(GuiInventory3x3Crafting.java:32)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73864_a(SourceFile:160)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1757)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1096)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.stats.RecipeBook.func_194075_d(RecipeBook.java:53)
	at net.minecraft.stats.RecipeBook.func_193830_f(RecipeBook.java:35)
	at net.minecraft.client.gui.recipebook.RecipeList.func_194210_a(SourceFile:34)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.lambda$updateCollections$0(GuiRecipeBook.java:161)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook$$Lambda$1285/212704632.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193003_g(GuiRecipeBook.java:159)
	at net.minecraft.client.gui.recipebook.GuiRecipeBook.func_193014_a(GuiRecipeBook.java:96)
	at net.minecraft.client.gui.inventory.GuiInventory.func_146284_a(SourceFile:182)
	at lordmonoxide.gradient.inventory.GuiInventory3x3Crafting.func_146284_a(GuiInventory3x3Crafting.java:32)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:323)
	at net.minecraft.client.gui.inventory.GuiInventory.func_73864_a(SourceFile:160)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: lordmonoxide.gradient.inventory.GuiInventory3x3Crafting

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Skeah'/83017, l='MpServer', x=169.30, y=71.00, z=100.84]]
	Chunk stats: MultiplayerChunkCache: 441, 441
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-100,64,256), Chunk: (at 12,4,0 in -7,16; contains blocks -112,0,256 to -97,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 39804378 game time, 8827808 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 158 total; [EntityCreeper['Creeper'/82949, l='MpServer', x=125.50, y=25.00, z=65.50], EntityPlayerSP['Skeah'/83017, l='MpServer', x=169.30, y=71.00, z=100.84], EntityZombie['Zombie'/82948, l='MpServer', x=125.50, y=25.00, z=58.50], EntityButterfly['Spicebush Swallowtail'/52491, l='MpServer', x=174.30, y=76.00, z=95.70], EntityBat['Bat'/83214, l='MpServer', x=114.74, y=21.10, z=152.26], EntityButterfly['Brimstone Moth'/52754, l='MpServer', x=183.30, y=79.00, z=111.78], EntityCreeper['Creeper'/81940, l='MpServer', x=179.50, y=37.00, z=105.50], EntityButterfly['Madeiran Speckled Wood'/65558, l='MpServer', x=174.20, y=83.00, z=110.65], EntityBat['Bat'/84249, l='MpServer', x=130.15, y=53.04, z=77.77], EntityPig['Pig'/69421, l='MpServer', x=194.51, y=64.00, z=32.66], EntitySheep['Sheep'/69420, l='MpServer', x=198.91, y=64.00, z=38.31], EntityMule['Frederickstein Von Mule III'/69422, l='MpServer', x=187.67, y=66.00, z=54.58], EntityItemFrame['entity.ItemFrame.name'/4404, l='MpServer', x=165.50, y=76.50, z=112.97], EntityItemFrame['entity.ItemFrame.name'/4405, l='MpServer', x=164.50, y=76.50, z=112.97], EntityItemFrame['entity.ItemFrame.name'/4406, l='MpServer', x=163.50, y=76.50, z=112.97], EntityButterfly['Citrus Swallowtail'/4663, l='MpServer', x=175.38, y=68.00, z=93.63], EntityItemFrame['entity.ItemFrame.name'/4407, l='MpServer', x=163.50, y=77.50, z=112.97], EntityItemFrame['entity.ItemFrame.name'/4408, l='MpServer', x=164.50, y=77.50, z=112.97], EntityHorse['Sarah Jessica Parkhorse'/4664, l='MpServer', x=179.23, y=64.00, z=27.17], EntityItemFrame['entity.ItemFrame.name'/4409, l='MpServer', x=165.50, y=77.50, z=112.97], EntityItemFrame['entity.ItemFrame.name'/4410, l='MpServer', x=165.50, y=78.50, z=112.97], EntityItemFrame['entity.ItemFrame.name'/4411, l='MpServer', x=164.50, y=78.50, z=112.97], EntityItemFrame['entity.ItemFrame.name'/4412, l='MpServer', x=163.50, y=78.50, z=112.97], EntityPainting['Painting'/4497, l='MpServer', x=174.97, y=73.50, z=95.50], EntityItemFrame['entity.ItemFrame.name'/4413, l='MpServer', x=162.50, y=76.50, z=112.97], EntityItemFrame['entity.ItemFrame.name'/4414, l='MpServer', x=162.50, y=77.50, z=112.97], EntityItemFrame['entity.ItemFrame.name'/4415, l='MpServer', x=162.50, y=78.50, z=112.97], EntityPainting['Painting'/4473, l='MpServer', x=174.50, y=70.50, z=98.03], EntitySheep['Sheep'/4419, l='MpServer', x=137.73, y=64.00, z=49.50], EntityPainting['Painting'/4474, l='MpServer', x=172.97, y=72.50, z=102.50], EntitySheep['Sheep'/4420, l='MpServer', x=127.51, y=64.00, z=57.19], EntityPainting['Painting'/4475, l='MpServer', x=170.00, y=72.00, z=108.97], EntityPainting['Painting'/4476, l='MpServer', x=172.97, y=72.50, z=105.50], EntityPainting['Painting'/4477, l='MpServer', x=172.97, y=72.50, z=106.50], EntityPainting['Painting'/4478, l='MpServer', x=172.97, y=72.50, z=103.50], EntityPainting['Painting'/4479, l='MpServer', x=172.97, y=72.50, z=104.50], EntityPainting['Painting'/4480, l='MpServer', x=172.97, y=72.50, z=101.50], EntityPainting['Painting'/4481, l='MpServer', x=173.50, y=69.50, z=108.97], EntityPainting['Painting'/4482, l='MpServer', x=173.03, y=69.50, z=105.00], EntityPainting['Painting'/4483, l='MpServer', x=175.97, y=69.50, z=101.50], EntityZombie['Zombie'/82508, l='MpServer', x=113.50, y=30.00, z=58.50], EntityPainting['Painting'/4484, l='MpServer', x=174.50, y=68.50, z=96.03], EntityPainting['Painting'/4485, l='MpServer', x=168.03, y=66.00, z=97.50], EntityBat['Bat'/82254, l='MpServer', x=140.75, y=19.10, z=42.54], EntityPainting['Painting'/4486, l='MpServer', x=172.97, y=65.50, z=98.00], EntityCreeper['Creeper'/80974, l='MpServer', x=175.30, y=47.00, z=125.70], EntityPainting['Painting'/4487, l='MpServer', x=168.03, y=73.00, z=99.00], EntityZombie['Zombie'/83029, l='MpServer', x=186.50, y=46.00, z=80.50], EntityZombie['Zombie'/83801, l='MpServer', x=138.50, y=24.00, z=137.50], EntitySheep['Sheep'/69723, l='MpServer', x=218.52, y=64.00, z=26.80], EntityBat['Bat'/83291, l='MpServer', x=137.29, y=24.16, z=166.17], EntityPig['Pig'/69724, l='MpServer', x=177.92, y=64.00, z=26.45], EntitySkeleton['Skeleton'/84063, l='MpServer', x=189.50, y=44.00, z=72.50], EntityZombie['Zombie'/82784, l='MpServer', x=126.50, y=14.00, z=26.50], EntityCreeper['Creeper'/84064, l='MpServer', x=190.50, y=44.00, z=70.50], EntitySkeleton['Skeleton'/84066, l='MpServer', x=106.50, y=36.00, z=27.50], EntityBat['Bat'/84322, l='MpServer', x=132.77, y=58.52, z=54.18], EntityCreeper['Creeper'/82788, l='MpServer', x=239.50, y=14.00, z=159.50], EntityCreeper['Creeper'/83815, l='MpServer', x=138.50, y=52.00, z=57.50], EntityOtherPlayerMP['Corielicious'/151, l='MpServer', x=65.83, y=63.00, z=246.41], EntityZombie['Zombie'/83817, l='MpServer', x=127.50, y=20.00, z=37.50], EntityZombie['Zombie'/84329, l='MpServer', x=176.50, y=50.00, z=62.50], EntityCreeper['Creeper'/83816, l='MpServer', x=133.80, y=52.00, z=63.49], EntityHorse['Cerberus'/4466, l='MpServer', x=139.06, y=63.00, z=136.14], EntityMule['Frederickstein Von Mule'/4467, l='MpServer', x=129.70, y=64.00, z=126.70], EntityHorse['Sotally Tober'/4468, l='MpServer', x=131.12, y=64.00, z=128.01], EntityHorse['Horsie McHorseFace'/4469, l='MpServer', x=143.00, y=63.00, z=134.07], EntityPainting['Painting'/4544, l='MpServer', x=176.97, y=70.00, z=104.50], EntityBat['Bat'/83574, l='MpServer', x=141.00, y=24.05, z=123.63], EntityBat['Bat'/82553, l='MpServer', x=141.66, y=23.77, z=118.36], EntityLadder['Stepladder'/4472, l='MpServer', x=168.73, y=64.00, z=97.24], EntityPainting['Painting'/4473, l='MpServer', x=174.50, y=70.50, z=98.03], EntityPainting['Painting'/4474, l='MpServer', x=172.97, y=72.50, z=102.50], EntityBat['Bat'/83579, l='MpServer', x=126.25, y=37.10, z=53.85], EntityPainting['Painting'/4475, l='MpServer', x=170.00, y=72.00, z=108.97], EntityPainting['Painting'/4476, l='MpServer', x=172.97, y=72.50, z=105.50], EntityBat['Bat'/82556, l='MpServer', x=134.68, y=28.50, z=157.03], EntityPainting['Painting'/4477, l='MpServer', x=172.97, y=72.50, z=106.50], EntityPainting['Painting'/4478, l='MpServer', x=172.97, y=72.50, z=103.50], EntityPainting['Painting'/4479, l='MpServer', x=172.97, y=72.50, z=104.50], EntityPainting['Painting'/4480, l='MpServer', x=172.97, y=72.50, z=101.50], EntityPainting['Painting'/4481, l='MpServer', x=173.50, y=69.50, z=108.97], EntitySquid['Squid'/81539, l='MpServer', x=164.34, y=61.79, z=61.35], EntityPainting['Painting'/4482, l='MpServer', x=173.03, y=69.50, z=105.00], EntitySquid['Squid'/81538, l='MpServer', x=169.11, y=59.21, z=69.36], EntityPainting['Painting'/4483, l='MpServer', x=175.97, y=69.50, z=101.50], EntityPainting['Painting'/4484, l='MpServer', x=174.50, y=68.50, z=96.03], EntityPainting['Painting'/4485, l='MpServer', x=168.03, y=66.00, z=97.50], EntitySquid['Squid'/81540, l='MpServer', x=182.87, y=58.85, z=74.47], EntityPainting['Painting'/4486, l='MpServer', x=172.97, y=65.50, z=98.00], EntityPainting['Painting'/4487, l='MpServer', x=168.03, y=73.00, z=99.00], EntityItemFrame['entity.ItemFrame.name'/4488, l='MpServer', x=171.97, y=73.50, z=102.50], EntityItemFrame['entity.ItemFrame.name'/4489, l='MpServer', x=171.97, y=73.50, z=101.50], EntityTFDeer['Wild Deer'/4490, l='MpServer', x=165.50, y=72.00, z=111.50], EntityBat['Bat'/82829, l='MpServer', x=131.38, y=54.10, z=59.49], EntityButterfly['Black Swallowtail'/9612, l='MpServer', x=156.01, y=63.00, z=145.62], EntityHorse['MayTheHorseBeWithYou'/4492, l='MpServer', x=178.83, y=64.00, z=102.29], EntityHorse['Token'/4493, l='MpServer', x=178.58, y=64.00, z=104.50], EntityHorse['There'sAnAppForThat'/4494, l='MpServer', x=141.47, y=63.00, z=142.33], EntityCreeper['Creeper'/83855, l='MpServer', x=130.65, y=28.00, z=153.79], EntityBat['Bat'/82830, l='MpServer', x=112.42, y=31.08, z=54.96], EntityDonkey['Shrek'/4495, l='MpServer', x=137.59, y=63.00, z=135.44], EntityZombie['Zombie'/83857, l='MpServer', x=129.50, y=27.00, z=161.50], EntityPainting['Painting'/4497, l='MpServer', x=174.97, y=73.50, z=95.50], EntityZombie['Zombie'/83856, l='MpServer', x=130.30, y=27.00, z=155.42], EntityButterfly['Brimstone Moth'/4498, l='MpServer', x=193.75, y=76.00, z=105.34], EntitySpider['Spider'/82578, l='MpServer', x=142.50, y=52.00, z=54.50], EntityCreeper['Creeper'/83858, l='MpServer', x=106.50, y=63.00, z=40.50], EntityButterfly['Brimstone Moth'/4500, l='MpServer', x=166.46, y=51.00, z=121.17], EntitySkeleton['Skeleton'/83860, l='MpServer', x=99.31, y=63.00, z=42.57], EntityZombie['Zombie'/83863, l='MpServer', x=103.59, y=63.00, z=33.81], EntityHorse['Actual Cannibal Shia LaHorse'/4503, l='MpServer', x=222.13, y=68.00, z=83.02], EntitySkeleton['Skeleton'/83865, l='MpServer', x=116.50, y=27.00, z=37.50], EntityButterfly['Palaeno Sulphur'/38810, l='MpServer', x=192.38, y=74.00, z=97.70], EntitySkeleton['Skeleton'/83355, l='MpServer', x=223.50, y=23.00, z=154.50], EntitySkeleton['Skeleton'/82074, l='MpServer', x=114.50, y=28.00, z=72.50], EntityBat['Bat'/84378, l='MpServer', x=92.06, y=51.03, z=50.39], EntityZombie['Zombie'/82589, l='MpServer', x=167.58, y=44.00, z=119.57], EntityCreeper['Creeper'/83101, l='MpServer', x=145.67, y=51.00, z=57.51], EntityCreeper['Creeper'/84381, l='MpServer', x=123.50, y=35.00, z=57.50], EntityZombie['Zombie'/82588, l='MpServer', x=177.50, y=46.00, z=124.25], EntityCreeper['Creeper'/83100, l='MpServer', x=140.75, y=52.00, z=56.64], EntityButterfly['Brimstone Moth'/82846, l='MpServer', x=178.84, y=63.33, z=91.33], EntityCreeper['Creeper'/84382, l='MpServer', x=125.50, y=35.00, z=58.50], EntityZombie['Zombie'/83105, l='MpServer', x=135.78, y=52.00, z=52.51], EntityZombie['Zombie'/84395, l='MpServer', x=149.50, y=29.00, z=86.50], EntitySpider['Spider'/84394, l='MpServer', x=149.50, y=29.00, z=84.50], EntityButterfly['Zebra Swallowtail'/33720, l='MpServer', x=176.00, y=68.00, z=118.84], EntityCreeper['Creeper'/80825, l='MpServer', x=168.48, y=44.00, z=118.13], EntityButterfly['Black Swallowtail'/4538, l='MpServer', x=183.31, y=85.00, z=106.87], EntityZombie['Zombie'/82874, l='MpServer', x=124.48, y=37.00, z=52.77], EntityPainting['Painting'/4544, l='MpServer', x=176.97, y=70.00, z=104.50], EntityDonkey['Kong'/4545, l='MpServer', x=174.96, y=64.00, z=100.99], EntityVillager['Villager'/4546, l='MpServer', x=181.54, y=80.00, z=109.29], EntityHorse['Notacow'/4547, l='MpServer', x=199.37, y=65.00, z=44.54], EntityBat['Bat'/81858, l='MpServer', x=209.54, y=34.10, z=31.75], EntityButterfly['Orange Tip'/33732, l='MpServer', x=154.71, y=63.00, z=140.27], EntityButterfly['Camberwell Beauty'/4548, l='MpServer', x=165.46, y=67.00, z=101.75], EntityButterfly['Zebra Swallowtail'/33733, l='MpServer', x=127.30, y=69.00, z=134.86], EntityButterfly['Brimstone Moth'/4549, l='MpServer', x=174.14, y=68.00, z=93.75], EntityButterfly['Meadow Brown'/4550, l='MpServer', x=174.09, y=63.00, z=139.81], EntityButterfly['Small Tortoiseshell'/4551, l='MpServer', x=152.25, y=74.00, z=135.75], EntityEnderman['Enderman'/83398, l='MpServer', x=146.50, y=17.00, z=48.50], EntityHorse['Dwayne "The Horse" Johnson'/4553, l='MpServer', x=202.13, y=68.00, z=92.84], EntityDonkey['JEEENNNNNNNNNKINNNNNNSSSSS'/4554, l='MpServer', x=201.35, y=65.00, z=43.41], EntityCreeper['Creeper'/82893, l='MpServer', x=178.80, y=39.00, z=123.41], EntityCreeper['Creeper'/83405, l='MpServer', x=214.50, y=34.00, z=35.50], EntityHorse['LEEEEEEEEEEEROOOOOOOOOOOYYYYYY'/4557, l='MpServer', x=211.12, y=68.00, z=76.15], EntityZombie['Zombie'/83663, l='MpServer', x=96.50, y=34.00, z=26.50], EntityZombie['Zombie'/82896, l='MpServer', x=130.50, y=17.00, z=77.50], EntityCreeper['Creeper'/83664, l='MpServer', x=99.50, y=34.00, z=25.50], EntityCreeper['Creeper'/83666, l='MpServer', x=99.50, y=34.00, z=22.50], EntitySpider['Spider'/82133, l='MpServer', x=91.50, y=55.00, z=25.50], EntityZombie['Zombie'/84447, l='MpServer', x=244.50, y=17.00, z=118.50], EntityZombie['Zombie'/84446, l='MpServer', x=244.50, y=17.00, z=116.50], EntityZombie['Zombie'/84462, l='MpServer', x=157.50, y=50.00, z=58.50], EntityCreeper['Creeper'/82427, l='MpServer', x=181.09, y=38.00, z=116.09], EntityHorse['Potoooooooo'/4606, l='MpServer', x=211.14, y=68.00, z=93.05]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2748)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1119503512 bytes (1067 MB) / 2669838336 bytes (2546 MB) up to 8482586624 bytes (8089 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
	IntCache: cache: 0, tcache: 0, allocated: 15, tallocated: 95
	FML: MCP 9.42 Powered by Forge 14.23.2.2618 Optifine OptiFine_1.12.2_HD_U_C9 36 mods loaded, 36 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version         | Source                                        | Signature                                |
	|:------ |:------------------- |:--------------- |:--------------------------------------------- |:---------------------------------------- |
	| UCHIJA | minecraft           | 1.12.2          | minecraft.jar                                 | None                                     |
	| UCHIJA | mcp                 | 9.42            | minecraft.jar                                 | None                                     |
	| UCHIJA | FML                 | 8.0.99.99       | forge-1.12.2-14.23.2.2618.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | forge               | 14.23.2.2618    | forge-1.12.2-14.23.2.2618.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJA | mercurius_updater   | 1.0             | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UCHIJA | bibliocraft         | 2.4.3           | BiblioCraft[v2.4.3][MC1.12.0].jar             | None                                     |
	| UCHIJA | ic2                 | 2.8.54-ex112    | industrialcraft-2-2.8.54-ex112.jar            | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJA | jei                 | 4.8.5.151       | jei_1.12.2-4.8.5.151.jar                      | None                                     |
	| UCHIJA | mantle              | 1.12-1.3.1.21   | Mantle-1.12-1.3.1.21.jar                      | None                                     |
	| UCHIJA | natura              | 1.12.2-4.3.2.42 | natura-1.12.2-4.3.2.42.jar                    | None                                     |
	| UCHIJA | forestry            | 5.8.0.250       | forestry_1.12.2-5.8.0.250.jar                 | None                                     |
	| UCHIJA | binniecore          | unspecified     | binnie-mods-1.12.2-2.5.0.112.jar              | None                                     |
	| UCHIJA | binniedesign        | 1.0             | binnie-mods-1.12.2-2.5.0.112.jar              | None                                     |
	| UCHIJA | genetics            | 2.5.0.112       | binnie-mods-1.12.2-2.5.0.112.jar              | None                                     |
	| UCHIJA | botany              | 2.5.0.112       | binnie-mods-1.12.2-2.5.0.112.jar              | None                                     |
	| UCHIJA | extrabees           | 2.5.0.112       | binnie-mods-1.12.2-2.5.0.112.jar              | None                                     |
	| UCHIJA | extratrees          | 2.5.0.112       | binnie-mods-1.12.2-2.5.0.112.jar              | None                                     |
	| UCHIJA | biomesoplenty       | 7.0.1.2314      | BiomesOPlenty-1.12.2-7.0.1.2314-universal.jar | None                                     |
	| UCHIJA | buildcraftlib       | 7.99.15         | buildcraft-7.99.15.jar                        | None                                     |
	| UCHIJA | buildcraftcore      | 7.99.15         | buildcraft-7.99.15.jar                        | None                                     |
	| UCHIJA | buildcraftbuilders  | 7.99.15         | buildcraft-7.99.15.jar                        | None                                     |
	| UCHIJA | buildcraftenergy    | 7.99.15         | buildcraft-7.99.15.jar                        | None                                     |
	| UCHIJA | buildcraftfactory   | 7.99.15         | buildcraft-7.99.15.jar                        | None                                     |
	| UCHIJA | buildcraftrobotics  | 7.99.15         | buildcraft-7.99.15.jar                        | None                                     |
	| UCHIJA | buildcraftsilicon   | 7.99.15         | buildcraft-7.99.15.jar                        | None                                     |
	| UCHIJA | buildcrafttransport | 7.99.15         | buildcraft-7.99.15.jar                        | None                                     |
	| UCHIJA | buildcraftcompat    | 7.99.14         | buildcraft-compat-7.99.14.jar                 | None                                     |
	| UCHIJA | codechickenlib      | 3.1.5.331       | CodeChickenLib-1.12.2-3.1.5.331-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | extrautils2         | 1.0             | extrautils2-1.12-1.7.4.jar                    | None                                     |
	| UCHIJA | fairylights         | 2.1.2           | fairylights-2.1.2-1.12.x.jar                  | None                                     |
	| UCHIJA | gradient            | ${version}      | gradient-0.0.1-0.jar                          | None                                     |
	| UCHIJA | ironchest           | 1.12-7.0.31.818 | ironchest-1.12-7.0.31.818.jar                 | None                                     |
	| UCHIJA | journeymap          | 1.12.2-5.5.2    | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UCHIJA | multimine           | 1.5.8           | MultiMine-1.12.2.jar                          | None                                     |
	| UCHIJA | nei                 | 2.4.1           | NotEnoughItems-1.12.2-2.4.1.233-universal.jar | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJA | twilightforest      | 3.6.345         | twilightforest-1.12.2-3.6.345-universal.jar   | None                                     |

	Loaded coremods (and transformers): 
MMFMLCorePlugin (MultiMine-1.12.2.jar)
  atomicstryker.multimine.common.fmlmagic.MMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Launched Version: 1.12.2-forge1.12.2-14.23.2.2618
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 750 Ti/PCIe/SSE2 GL version 4.6.0 NVIDIA 388.13, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz
	OptiFine Version: OptiFine_1.12.2_HD_U_C9
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 388.13
	OpenGlRenderer: GeForce GTX 750 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4
```

**Comment by LordMonoxide** [comment]
This was a version conflict
