### ISSUE TITLE
Bronze boiler crash when trying to fill with water from fluid bladder

### ISSUE THREAD

**Issue by LordMonoxide** [LordMonoxide/gradient#660]
```
[18:01:17] [Server thread/WARN] [FML]: ****************************************
[18:01:17] [Server thread/WARN] [FML]: * Null fluid supplied to fluidstack. Did you try and create a stack for an unregistered fluid?
[18:01:17] [Server thread/WARN] [FML]: *  at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:48)
[18:01:17] [Server thread/WARN] [FML]: *  at lordmonoxide.gradient.tileentities.TileBronzeBoiler.boilWater(TileBronzeBoiler.java:106)
[18:01:17] [Server thread/WARN] [FML]: *  at lordmonoxide.gradient.tileentities.TileBronzeBoiler.tickAfterCooldown(TileBronzeBoiler.java:83)
[18:01:17] [Server thread/WARN] [FML]: *  at lordmonoxide.gradient.blocks.heat.HeatSinker.update(HeatSinker.java:75)
[18:01:17] [Server thread/WARN] [FML]: *  at net.minecraft.world.World.updateEntities(World.java:2019)
[18:01:17] [Server thread/WARN] [FML]: *  at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:643)...
[18:01:17] [Server thread/WARN] [FML]: ****************************************
[18:01:17] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Ticking block entity
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:848) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:415) ~[DedicatedServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:743) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:592) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
	at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:49) ~[FluidStack.class:?]
	at lordmonoxide.gradient.tileentities.TileBronzeBoiler.boilWater(TileBronzeBoiler.java:106) ~[TileBronzeBoiler.class:?]
	at lordmonoxide.gradient.tileentities.TileBronzeBoiler.tickAfterCooldown(TileBronzeBoiler.java:83) ~[TileBronzeBoiler.class:?]
	at lordmonoxide.gradient.blocks.heat.HeatSinker.update(HeatSinker.java:75) ~[HeatSinker.class:?]
	at net.minecraft.world.World.updateEntities(World.java:2019) ~[World.class:?]
	at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:643) ~[WorldServer.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:842) ~[MinecraftServer.class:?]
	... 4 more
```

**Comment by LordMonoxide** [comment]
Closed with #661
